### ISSUE TITLE
Aira package for offsetting agent without calculation

### ISSUE THREAD

**Issue by ensrationis** [DAO-IPCI/complier_service#10]
Now offsetting agent can calculate carbon footprint based on info about electricity consumption. We need new and more simply logic for agent, where agent will work with data about carbon footprint in tCO2.

**Comment by Vourhey** [comment]
Added `tons` branch to implement this feature https://github.com/DAO-IPCI/offsetting_agent/tree/tons

**Comment by ensrationis** [comment]
Thanks!
